Feature documentation
SmartEnergyOrg/Backend pull request #76
Opened 2023-01-16 18:14 UTC by geoduin

2023-01-17 11:52 UTC, JensdeVlaming requested changes
Aantal opmerkingen:

1. Backend/Backend snap ik niet helemaal. Als je de code pullt dan komt je direct op /backend uit.
2. Het is niet backend maar backend-main. 
3. Veelgestelde vragen lijken mij overbodig.

2023-01-18 11:05 UTC, sylvesterroos commented on MANUAL.md
> +|Xin|Silvester|Marcello|Jens|Mick|Joost|
Sylvester* ;)

2023-01-18 11:05 UTC, Pistrie commented on MANUAL.md
> +4. Navigeer vanuit de root folder, direct naar de Backend folder via de volgende commando
Iets zeggen als "navigeer vervolgens naar de root van het backend project (waar het `install.sh` bestand staat) ipv de directe commandos"

2023-01-18 11:05 UTC, Pistrie commented on MANUAL.md
> +Deze commando installeert docker en de bijbehorende docker container en packages.
Dit* commando

2023-01-18 11:05 UTC, Pistrie commented on MANUAL.md
> +**Let op!** Als het apparaat geen editor heeft geïnstalleerd, dan zal het installatiescript een foutmelding teruggeven.
Het gaat om een _command line_ editor. Als deze niet is ingesteld geeft het commando een foutmelding. Een terminal hoeft niet gedownload te worden want die bestaat per definitie, immers de installateur gebruikt dit script in een terminal

2023-01-18 11:05 UTC, Pistrie commented on MANUAL.md
> +Als het installatiescript zonder fouten uitgevoerd is, dan start applicatie automatisch op en kan er gebruik gemaakt worden.
... gebruikt gemaakt van worden.*

2023-01-18 11:05 UTC, Pistrie commented on MANUAL.md
> +npm run dev
Het is `npm run start`

2023-01-19 08:45 UTC, JensdeVlaming approved these changes

2023-01-19 08:45 UTC, merged